config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :materials
  resources :cocktails
end

app/models/cocktail.rb
# == Schema Information
#
# Table name: cocktails
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  name_en    :string(255)
#  taste      :string(255)
#  technic    :string(255)
#  tpo        :string(255)
#  glass      :string(255)
#  base       :string(255)
#  volume     :integer
#  created_at :datetime
#  updated_at :datetime
#

class Cocktail < ActiveRecord::Base
  has_many :materials, through: :ingredient
  has_one :ingredient
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  cocktail_id :integer
#  material_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Ingredient < ActiveRecord::Base
  has_one :cocktail
  belongs_to :material
end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Material < ActiveRecord::Base
  belongs_to :ingredient

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save!

    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :name_en, :taste, :technique, :tpo, :glass, :base, :volume)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
    @materials = Material.all
  end
  def new
    @material = Material.new
  end
  def create
    @material = Material.new(material_params)
    @material = nil unless @material.save
    unless @material
      render :new and return
    end
    redirect_to materials_path
  end

  private

  def material_params
    params.require(:material).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktaiils_helper.rb
module CocktaiilsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/cocktails/_form.html.slim
.form-group
  = f.label :name, "名前"
  = f.text_field :name, class: "form-control"

.form-group
  = f.label :name_en, "英名"
  = f.text_field :name_en, class: "form-control"

.form-group
  = f.label :taste, "テイスト"
  = f.text_field :taste, class: "form-control"

.form-group
  = f.label :technique, "技法"
  = f.text_field :technique, class: "form-control"

.form-group
  = f.label :tpo, "TPO"
  = f.text_field :tpo, class: "form-control"

.form-group
  = f.label :glass, "グラスの種類"
  = f.text_field :glass, class: "form-control"

.form-group
  = f.label :base, "ベース (ノンアルコールの場合は空にしてください)"
  = f.text_field :base, class: "form-control"

.form-group
  = f.label :volume, "度数"
  = f.text_field :volume, class: "form-control"

app/views/cocktails/index.html.slim
h2 カクテル一覧

= link_to "登録", new_cocktail_path, class: "btn btn-success add-button"

.row
  - @cocktails.each do |cocktail|
    .col-md-6
      .cocktail-item
        .cocktail-item-header
          span.h4.name #{cocktail.name}
          span.taste.label.label-info #{cocktail.taste}
          span.technique.label.label-success #{cocktail.technique}

        .cocktail-item-content
          .row
            ul
              .col-md-6
                li
                  span = cocktail.taste
              .col-md-6
                li
                  span = cocktail.technique
              .col-md-6
                li
                  span = cocktail.tpo
              .col-md-6
                li
                  span = cocktail.glass
              .col-md-6
                li
                  span = cocktail.base
              .col-md-6
                li
                  span.volume = cocktail.volume
        .cocktail-ingredients
          .header 材料
          ul
            .raw
              - cocktail.materials.each do |mat|
                li.col-md-6 = mat.name

app/views/cocktails/new.html.slim
h2 カクテル登録

= form_for @cocktail do |f|
  = render 'form', f: f

  = f.submit "登録", "data-role" => "none", class: "btn btn-primary"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rcall
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default
      .container-fluid
        .navber-header
          a.navbar-brand href="/" Brand
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to "カクテル", cocktails_path
            li
              = link_to "材料", materials_path

    .container-fluid
      = yield

app/views/materials/index.html.slim
h2 材料一覧

= link_to "作成", new_material_path, class: "btn btn-success add-button"

ul
  - @materials.each do |material|
    li = material.name

app/views/materials/new.html.slim
h2 材料追加

= form_for @material do |f|
  .field
    = f.text_field :name, autofocus: true
  .field
    = f.submit "確認", class: "ui submit blue button"